#! /usr/bin/env python3
"""ferengi.

    Greedy data acquisition.

Usage:
    ferengi openweathermap [options]
    ferengi garbage-disposal [options]

Options:
    --force, -f     Force data import.
    --help, -h      Show this page.
"""
from logging import INFO, basicConfig
from sys import argv, stderr, exit as exit_

from docopt import docopt

from ferengi.api import APIError, roa
from ferengi.garbage_disposal import GarbageDisposal
from ferengi.openweathermap import City


def main(options):
    """Runs the FERENGI client."""

    basicConfig(level=INFO)
    force = options['--force']

    if options['openweathermap']:
        try:
            City.update_all()
        except APIError as api_error:
            print('Caught API error ({}): {}'.format(
                int(api_error), str(api_error)), file=stderr)
            return 1
    elif options['garbage-disposal']:
        try:
            GarbageDisposal.update_all()
        except APIError as api_error:
            print('Caught API error ({}): {}'.format(
                int(api_error), str(api_error)), file=stderr)
            return 1

    return 0


if __name__ == '__main__':
    if '--rules-of-acquisition' in argv:
        print(roa())
        exit_(0)
    else:
        exit_(main(docopt(__doc__)))
