#! /usr/bin/env python3
"""ferengi

Greedy data acquisition

Usage:
    ferengi openweathermap [options]
    ferengi wettercom [options]

Options:
    --help, -h          Show this page.
    --force, -f         Force data import.
"""
from sys import stderr, exit as exit_
from docopt import docopt
from ferengi.api import APIError


def main(options):
    """Runs the FERENGI client."""

    force = options['--force']

    if options['openweathermap']:
        from ferengi.openweathermap import City

        try:
            City.update_all()
        except APIError as api_error:
            print('Caught API error ({}): {}'.format(
                int(api_error), str(api_error)), file=stderr)
            return 1
    elif options['wettercom']:
        from ferengi.wettercom import City

        try:
            City.update_all()
        except APIError as api_error:
            print('Caught API error ({}): {}'.format(
                int(api_error), str(api_error)), file=stderr)
            return 1

    return 0


if __name__ == '__main__':
    exit_(main(docopt(__doc__)))
