#! /usr/bin/env python3
"""ferengi.

    Greedy data acquisition.

Usage:
    ferengi garbage-disposal [options]
    ferengi openligadb [options]
    ferengi openweathermap [options]

Options:
    --force, -f     Force data import.
    --help, -h      Show this page.
"""
from logging import INFO, basicConfig, getLogger
from sys import argv, exit as exit_

from docopt import docopt

from ferengi.api import APIError, roa
from ferengi.garbage_disposal import Location
from ferengi.openligadb import Team
from ferengi.openweathermap import City


LOGGER = getLogger(__file__)


def main(options):
    """Runs the FERENGI client."""

    basicConfig(level=INFO)
    force = options['--force']

    if options['garbage-disposal']:
        Location.update_all(force=force)
    elif options['openligadb']:
        Team.update_from_api()
    elif options['openweathermap']:
        try:
            City.update_all()
        except APIError as api_error:
            LOGGER.error(
                'Caught API error (%i): %s.', int(api_error), str(api_error))
            return 1

    return 0


if __name__ == '__main__':
    if '--rules-of-acquisition' in argv:
        print(roa())
        exit_(0)
    else:
        exit_(main(docopt(__doc__)))
